name: WIF
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'bilvantisaimlproject'
        workload_identity_provider: 'projects/286895835019/locations/global/workloadIdentityPools/github-wif/providers/test-repo'
    
    - name: Terraform Init
      uses: hashicorp/setup-terraform@v2
      run: cd Terraform && terraform init

    - name: Terraform Plan
      uses: hashicorp/setup-terraform@v2
      run: cd Terraform && terraform plan

    - name: Terraform Apply
      uses: hashicorp/setup-terraform@v2
      run: cd Terraform && terraform apply -auto-approve